### ISSUE TITLE
ImportError when run code after docker build

### ISSUE THREAD

**Issue by bb78657** [CosmiQ/CosmiQ_SN4_Baseline#3]
I have used the process below to build a CosmiQ_SN4_Baseline docker image on two separate Ubuntu 16.04 machines and get the same error.

commands:

```
git clone https://github.com/CosmiQ/CosmiQ_SN4_Baseline.git
cd CosmiQ_SN4_Baseline/
nvidia-docker build -t cosmiq_sn4_baseline .
NV_GPU=0 nvidia-docker run -it --name space_base cosmiq_sn4_baseline
python make_rgbs.py --dataset_dir my_dta_dir --output_dir my_out_dir
```

```
>>Traceback (most recent call last):
  File "make_rgbs.py", line 12, in <module>
    import cosmiq_sn4_baseline as space_base
  File "/tmp/src/cosmiq-sn4-baseline-1.1.1/cosmiq_sn4_baseline/__init__.py", line 1, in <module>
    from .utils import *
  File "/tmp/src/cosmiq-sn4-baseline-1.1.1/cosmiq_sn4_baseline/utils/__init__.py", line 1, in <module>
    from .rgb import *
  File "/tmp/src/cosmiq-sn4-baseline-1.1.1/cosmiq_sn4_baseline/utils/rgb.py", line 2, in <module>
    import rasterio
  File "/opt/conda/envs/space_base/lib/python3.6/site-packages/rasterio/__init__.py", line 23, in <module>
    from rasterio._base import gdal_version
ImportError: /opt/conda/envs/space_base/lib/python3.6/site-packages/rasterio/../../.././libkea.so.1.4: undefined symbol: _ZNK2H58H5Object13openAttributeERKSs
```

**Comment by nrweir** [comment]
Hi bb78657,

Looks like there's something weird going on with your rasterio/GDAL install. From googling the end of your `ImportError`, this seems to be a common theme:
1. When working outside of the conda environment specified for package installs
2. When some packages are installed from conda-forge and some from the default channel

Let me ask to corresponding questions:
1. are you in the `space_base` environment when you run the `python make_rgbs.py` command? If so,
2. Can you drop the output from your `nvidia-docker build` command here (or at least the piece of it where it pulls down the conda packages)?

**Comment by bb78657** [comment]
I can confirm that I am in space_base when I run (space_base) root@a85038703ee4:/tmp# cd src/cosmiq-sn4-baseline-1.1.1/bin
then:
(space_base) root@a85038703ee4:/tmp/src/cosmiq-sn4-baseline-1.1.1/bin# python make_rgbs.py --dataset_dir in_dir --output_dir  out_dir

running build again:

Sending build context to Docker daemon  4.832MB
Step 1/25 : FROM nvidia/cuda:9.0-devel-ubuntu16.04
 ---> 07f3fc56927f
Step 2/25 : MAINTAINER nweir <nweir@iqt.org>
 ---> Using cache
 ---> f190741c2454
Step 3/25 : ENV CUDNN_VERSION 7.3.0.29
 ---> Using cache
 ---> 76dfb7c86c6c
Step 4/25 : LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"
 ---> Using cache
 ---> 77f30561c205
Step 5/25 : RUN apt-get update && apt-get install -y --no-install-recommends 	    apt-utils             libcudnn7=$CUDNN_VERSION-1+cuda9.0             libcudnn7-dev=$CUDNN_VERSION-1+cuda9.0 &&     apt-mark hold libcudnn7 &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> fdda5b754990
Step 6/25 : RUN apt-get update   && apt-get install -y --no-install-recommends     bc     bzip2     ca-certificates     curl     git     libgdal-dev     libssl-dev     libffi-dev 		libncurses-dev     libgl1     jq     nfs-common     parallel     python-dev     python-pip     python-wheel     python-setuptools     unzip 		vim     wget     build-essential   && apt-get clean   && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> bc4ba53ec810
Step 7/25 : SHELL ["/bin/bash", "-c"]
 ---> Using cache
 ---> 95df764dfcaf
Step 8/25 : ENV PATH /opt/conda/bin:$PATH
 ---> Using cache
 ---> 66d7d92e71a6
Step 9/25 : RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh -O ~/miniconda.sh &&     /bin/bash ~/miniconda.sh -b -p /opt/conda &&     rm ~/miniconda.sh &&     /opt/conda/bin/conda clean -tipsy &&     ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh &&     echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc &&     echo "conda activate base" >> ~/.bashrc
 ---> Using cache
 ---> 513b0abce5d0
Step 10/25 : ENV TINI_VERSION v0.16.1
 ---> Using cache
 ---> 9666de444afb
Step 11/25 : ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
Downloading [==================================================>]  19.97kB/19.97kB
 ---> Using cache
 ---> 81fc9eadf13f
Step 12/25 : RUN chmod +x /usr/bin/tini
 ---> Using cache
 ---> 6c5939c4d866
Step 13/25 : RUN conda update conda &&     conda config --remove channels defaults &&     conda config --add channels conda-forge
 ---> Using cache
 ---> d6fd9d30baff
Step 14/25 : RUN conda create -n space_base python=3.6                     && echo "source activate space_base" > ~/.bashrc
 ---> Using cache
 ---> 9c2a16f63580
Step 15/25 : ENV PATH /opt/conda/envs/space_base/bin:$PATH
 ---> Using cache
 ---> 75b2cd587c08
Step 16/25 : RUN source activate space_base &&     conda install -n space_base -c defaults tensorflow-gpu
 ---> Using cache
 ---> c0358efa736e
Step 17/25 : ENV KERAS_BACKEND=tensorflow
 ---> Using cache
 ---> aab6f06421f2
Step 18/25 : RUN source activate space_base   && conda install -n space_base keras
 ---> Using cache
 ---> 29a1f0554e61
Step 19/25 : RUN conda install -n space_base               awscli               osmnx=0.7.3               affine               pyproj               pyhamcrest=1.9.0               cython               fiona               h5py               ncurses               jupyter               jupyterlab               ipykernel               libgdal               matplotlib 							ncurses               numpy               opencv               pandas               pillow               pip               scipy               scikit-image               scikit-learn               shapely               gdal               rtree               testpath               tqdm               pandas               geopandas               rasterio
 ---> Using cache
 ---> de547466e585
Step 20/25 : RUN source activate space_base && python -m ipykernel.kernelspec
 ---> Using cache
 ---> ffb88d4e3dd1
Step 21/25 : EXPOSE 8888 6006
 ---> Using cache
 ---> b53ad02ade83
Step 22/25 : WORKDIR /tmp/
 ---> Using cache
 ---> 41732cebf9cd
Step 23/25 : RUN git clone https://github.com/SpaceNetChallenge/utilities.git && cd utilities &&     git checkout spacenetV3 &&     source activate space_base &&     pip install --no-cache-dir --no-dependencies -e .
 ---> Using cache
 ---> 9b7dd6c0a29d
Step 24/25 : RUN source activate space_base && 	  pip install -e git+git://github.com/cosmiq/cosmiq_sn4_baseline.git@1.1.1#egg=cosmiq_sn4_baseline-1.1.1
 ---> Using cache
 ---> 922d243f8960
Step 25/25 : RUN ["/bin/bash"]
 ---> Using cache
 ---> 0945133b94a5
Successfully built 0945133b94a5
Successfully tagged cosmiq_sn4_baseline:latest

**Comment by nrweir** [comment]
I made a couple of updates to the Dockerfile and setup.py which may resolve your issues - can you `git pull origin master` followed by re-building the docker image? When you re-build, please use the `--no-cache` flag to make sure it re-builds fresh.

**Comment by bb78657** [comment]
Thats fixed it
