### ISSUE TITLE
Could not detect requirement name, please specify one with #egg=

### ISSUE THREAD

**Issue by archenroot** [CosmiQ/CosmiQ_SN4_Baseline#4]
i get this error when trying: pip3 install --user -e git+git://github.com/cosmiq_sn4_baseline

**Comment by nrweir** [comment]
Sorry about the delayed response, and apologies for the typo in the install instructions. Instead, use:

```
pip3 install --user -e git+git://github.com/cosmiq/cosmiq_sn4_baseline#egg=cosmiq_sn4_baseline
```
